# Generated by Django 3.2.5 on 2021-07-30 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listapi', '0002_addressdetails_phonedetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhoneDetails',
        ),
    ]
